// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xowS-FnGVqx4ZZIbnmAxvtTaNtdn-gc',
    appId: '1:136027866510:web:7777e3d0d374d8af6510df',
    messagingSenderId: '136027866510',
    projectId: 'gamesphere-14b89',
    authDomain: 'gamesphere-14b89.firebaseapp.com',
    storageBucket: 'gamesphere-14b89.firebasestorage.app',
    measurementId: 'G-1KNYP7ERTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApFCysU64pKH8MML6l3CliV_wgl_XeCuA',
    appId: '1:136027866510:android:6bfca9982785c4a16510df',
    messagingSenderId: '136027866510',
    projectId: 'gamesphere-14b89',
    storageBucket: 'gamesphere-14b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1VwuVBTtAgwDMgoVRHxDH8HYHGtBfmQs',
    appId: '1:136027866510:ios:34fa05d222889e746510df',
    messagingSenderId: '136027866510',
    projectId: 'gamesphere-14b89',
    storageBucket: 'gamesphere-14b89.firebasestorage.app',
    iosBundleId: 'com.example.gamesphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1VwuVBTtAgwDMgoVRHxDH8HYHGtBfmQs',
    appId: '1:136027866510:ios:34fa05d222889e746510df',
    messagingSenderId: '136027866510',
    projectId: 'gamesphere-14b89',
    storageBucket: 'gamesphere-14b89.firebasestorage.app',
    iosBundleId: 'com.example.gamesphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1xowS-FnGVqx4ZZIbnmAxvtTaNtdn-gc',
    appId: '1:136027866510:web:3405b7b1c1fcce116510df',
    messagingSenderId: '136027866510',
    projectId: 'gamesphere-14b89',
    authDomain: 'gamesphere-14b89.firebaseapp.com',
    storageBucket: 'gamesphere-14b89.firebasestorage.app',
    measurementId: 'G-NYXJG2HPHY',
  );
}
